### ISSUE TITLE
Unable to fetch organization

### ISSUE THREAD

**Issue by llarco** [kevinwortman/nerfherder#1]
When running the clone-organization program, I get the following error:

```
./clone-organization login=llarco org=CSUF-CPSC-120-LW
GitHub password:
INFO:root:fetching organization org=CSUF-CPSC-120-LW
Traceback (most recent call last):
  File "./clone-organization", line 69, in <module>
    main()
  File "./clone-organization", line 25, in main
    org = the_github.get_organization(args.org)
  File "/usr/local/lib/python3.7/site-packages/github/MainClass.py", line 249, in get_organization
    "/orgs/" + login
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 260, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 271, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/orgs/#get-an-organization'}
```

Looking at the code, it seems that line 25 calls the method get_organization() passing the organization name as a parameter. However, when looking at the documentation of get_organization(), I see that it expects a "login" string: https://pygithub.readthedocs.io/en/latest/github.html#github.MainClass.Github.get_organization

No idea what the "login" string is, but I guess passing the organization name (which I believe it's unique) doesn't work.

I tried calling get_user().get_orgs() and was able to retrieve some organizations, but only the id was populated, and not the name.

**Comment by llarco** [comment]
Closing the issue as the program is working as intended. I was not passing the arguments correctly.

**Comment by kevinwortman** [comment]
OK, glad to hear it's working for you now. Do you think changing the documentation would make it clearer how to format the arguments?

**Comment by llarco** [comment]
Providing a sample way to run the command would be helpful. I was running it as `./clone-organization login=llarco org=CSUF-CPSC-120-LW` which was setting `login` to "login=llarco" and `org` to "org=CSUF-CPSC-120-LW".

**Comment by kevinwortman** [comment]
Added a usage example highlighting this issue to README.md in commit d62864802a4eb4df84fe830a4c5bbed450c01015 .
